[package]
name = "app"
version = "2026.7.0"
edition = "2024"
build = "build.rs"

[dependencies]
rustls = { version = "0.23", features = ["ring"] }
linux = { path = "../linux", optional = true }

[features]
force-gtk-run = ["dep:linux"]

[target.'cfg(target_os = "windows")'.dependencies]
windows = { path = "../windows" }

[target.'cfg(target_os = "windows")'.build-dependencies]
windows-reactor-setup = { git = "https://github.com/microsoft/windows-rs", rev = "dc720b3674c46ceb82d758ed20959977b32e60a9" }

[target.'cfg(target_os = "macos")'.dependencies]
macos = { path = "../macos" }

[target.'cfg(target_os = "linux")'.dependencies]
linux = { path = "../linux" }