[package]
name = "app"
version = "2026.7.0"
edition = "2024"
build = "build.rs"

[dependencies]
rustls = { version = "0.23", features = ["ring"] }
tokio = { version = "1", features = ["full"] }
linux = { path = "../linux", optional = true }

[features]
force-gtk-run = ["dep:linux"]

[target.'cfg(target_os = "windows")'.dependencies]
windows = { path = "../windows" }

[target.'cfg(target_os = "macos")'.dependencies]
macos = { path = "../macos" }

[target.'cfg(target_os = "linux")'.dependencies]
linux = { path = "../linux" }