[package]
name = "linux"
version = "2026.7.0"
edition = "2024"
build = "build.rs"

[dependencies]
adw = { package = "libadwaita", version = "0.9", features = ["v1_9"] }
gtk = { package = "gtk4", version = "0.11", features = ["v4_22", "gnome_50"] }
glib = "0.22"
glib-unix = "0.22"
gio = "0.22"
gio-unix = { version = "0.22", features = ["v2_84"] }
shared = { path = "../shared" }

[build-dependencies]
glib-build-tools = "0.22"