name: application 
base: core24
adopt-info: application
grade: stable
confinement: strict
compression: lzo

lint:
  ignore:
    - classic
    - library

parts:
  deps:
    plugin: nil
    stage-packages:
      - libstdc++6
      - libboost-system1.83.0
      - libboost-json1.83.0
      - libsqlcipher-dev
    prime:
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libstdc++*.so*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libboost_system.so*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libboost_json.so*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libsqlcipher.so*

  cpr:
    source: https://github.com/libcpr/cpr.git
    source-commit: 'b14cd346bf3657ac046ebde136bd9300ce885c5e'
    source-depth: 1
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCPR_BUILD_TESTS=OFF
      - -DCPR_USE_SYSTEM_CURL=ON
      - -DCPR_ENABLE_SSL=ON
    override-prime: ''

  maddy:
    source: https://github.com/progsource/maddy.git
    source-tag: '1.5.0'
    source-depth: 1
    plugin: dump
    override-prime: '' 

  libnick:
    after: [cpr, maddy]
    source: https://github.com/nickvisionapps/libnick.git
    source-tag: "2025.7.1"
    source-depth: 1
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_TESTING=OFF
      - -DCMAKE_BUILD_TYPE=Release
    build-environment:    
      - CMAKE_PREFIX_PATH: ${CRAFT_STAGE}/usr${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH}
    build-packages:
      - libssl-dev
      - uuid-dev
      - libboost-dev
      - libboost-system1.83-dev
      - libboost-json1.83-dev
      - libsqlcipher-dev
    override-prime: ''

  libxmlplusplus:
    source: https://github.com/libxmlplusplus/libxmlplusplus.git
    source-tag: '5.4.0'
    source-depth: 1
    plugin: meson
    build-packages:
      - libicu-dev
    meson-parameters:
      - --prefix=/usr
      - -Dmaintainer-mode=false
    prime:
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libxml++-5.0*.so*

  application:
    after: [maddy, libnick, libxmlplusplus]
    plugin: cmake
    source: .
    build-snaps:
      - cmake
      - blueprint-compiler
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/snap/application/current/usr
      - -DCMAKE_BUILD_TYPE=Release
    stage-packages:
      - libstdc++6
    build-environment:
      - CMAKE_PREFIX_PATH: ${CRAFT_STAGE}/usr${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH}
    parse-info: [usr/share/metainfo/org.nickvision.application.metainfo.xml]
    organize:
      snap/application/current: .

slots:
  application:
    interface: dbus
    bus: session
    name: org.nickvision.application

apps:
  application:
    command: usr/lib/org.nickvision.application/org.nickvision.application.gnome
    desktop: usr/share/applications/org.nickvision.application.desktop
    common-id: org.nickvision.application
    extensions: [gnome]
    plugs:
      - unity7
