name: application
base: core24
adopt-info: application
grade: devel
confinement: strict
compression: lzo

lint:
  ignore:
    - classic
    - library

parts:
  blueprint-compiler:
    source-depth: 1
    source: https://gitlab.gnome.org/jwestman/blueprint-compiler.git
    source-tag: "v0.12.0"
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    override-prime: ""

  build-deps:
    plugin: nil
    build-packages:
      - g++-13
      - gcc-13
      - libjsoncpp-dev
      - libstdc++6

  deps:
    after: [build-deps]
    plugin: nil
    stage-packages:
      - libjsoncpp25
      - libstdc++6
    prime:
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libstdc++*.so*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libjsoncpp*

  maddy:
    after: [build-deps]
    source: https://github.com/progsource/maddy.git
    source-tag: "1.3.0"
    plugin: dump
    source-depth: 1
    override-prime: ""

  libnick:
    after: [maddy, build-deps]
    source: https://github.com/nickvisionapps/libnick.git
    source-tag: "2024.3.0"
    source-depth: 1
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_TESTING=OFF
      - -DCMAKE_BUILD_TYPE=Release
    build-environment:
      - CPLUS_INCLUDE_PATH: ${CRAFT_STAGE}/include
    build-packages:
      - libssl-dev
      - uuid-dev
    override-prime: ""

  libxmlplusplus:
    after: [build-deps]
    source: https://github.com/libxmlplusplus/libxmlplusplus.git
    source-tag: "5.2.0"
    source-depth: 1
    plugin: meson
    build-packages:
      - libicu-dev
    meson-parameters:
      - --prefix=/usr
      - -Dmaintainer-mode=false
    prime:
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libxml++-5.0*.so*

  application:
    after: [build-deps, maddy, libnick, libxmlplusplus, blueprint-compiler]
    plugin: cmake
    source: .
    build-snaps:
      - cmake
      - gnome-46-2404-sdk/latest/edge
      - gnome-46-2404/latest/edge
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/snap/application/current/usr
      - -DCMAKE_BUILD_TYPE=Release
    build-packages:
      - libvulkan-dev
    stage-packages:
      - libstdc++6
    build-environment:
      - CMAKE_PREFIX_PATH: ${CRAFT_STAGE}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/cmake${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH}
      - PYTHONPATH: $CRAFT_STAGE/usr/lib/python3/dist-packages:$PYTHONPATH
      - GI_TYPELIB_PATH: /snap/gnome-46-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:/snap/gnome-46-2404-sdk/current/usr/lib/girepository-1.0
    parse-info: [usr/share/metainfo/org.nickvision.application.metainfo.xml]
    organize:
      snap/application/current: .

slots:
  application:
    interface: dbus
    bus: session
    name: org.nickvision.application

apps:
  application:
    command: usr/lib/org.nickvision.application/org.nickvision.application.gnome
    desktop: usr/share/applications/org.nickvision.application.desktop
    common-id: org.nickvision.application
    extensions: [gnome]
    plugs:
      - unity7
