on: ["push", "pull_request"]
name: Codacy
jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master