on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Flatpak
jobs:
  gnome-flatpak:
    name: "GNOME on Flatpak"
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login != 'weblate' }}
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    strategy:
      matrix:
        # As of the time of writing (February 2023), GitHub Actions only provides x86_64 runners. While Flatpak does
        # provide cross-building for other architectures, it uses QEMU to do so, and dotnet does not play well under
        # QEMU for arm64. See below links for potential updates:
        # - https://github.com/dotnet/runtime/issues/13648
        # - https://github.com/actions/runner-images/issues/5631
        arch: [x86_64]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          submodules: recursive
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
        with:
          bundle: org.nickvision.application.flatpak
          manifest-path: flatpak/org.nickvision.application.json
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}
          restore-cache: true
