on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
  workflow_call:
    inputs:
      tag:
        description: "Git ref to check out"
        type: string
        required: true
name: Flatpak
permissions:
  id-token: write
  contents: read
jobs:
  flatpak:
    name: "Tauri on Flatpak"
    if: ${{ github.event.pull_request.user.login != 'weblate' }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-51
      options: --privileged
    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ inputs.tag || github.ref_name }}
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: org.nickvision.application.${{ matrix.variant.arch }}.flatpak
          manifest-path: build-aux/flatpak/org.nickvision.application.json
          cache-key: flatpak-builder-${{ inputs.tag || github.sha }}
          arch: ${{ matrix.variant.arch }}
          restore-cache: true
          verbose: true
          artifact-name: org.nickvision.application.${{ matrix.variant.arch }}.flatpak
