on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Flatpak
permissions:
  id-token: write
  contents: read
jobs:
  gnome-flatpak:
    name: "GNOME on Flatpak"
    runs-on: ubuntu-latest
    container: 
      image: opensuse/tumbleweed:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Environment"
        run: |
          mkdir build
          mkdir repo
          zypper ref -b && zypper dup -y
          zypper in -y curl zip unzip tar wget blueprint-compiler gtk4-devel libadwaita libadwaita-devel xdg-desktop-portal-gnome webp-pixbuf-loader gettext flatpak flatpak-builder flatpak-xdg-utils xdg-utils xdg-user-dirs xdg-user-dirs-gtk git cmake cpp gcc gcc-c++ autoconf automake
          xdg-user-dirs-update
          xdg-user-dirs-gtk-update
      - name: "Flatpak"
        run: |
          flatpak-builder --repo=repo --force-clean build flatpak/org.nickvision.application.json
          flatpak build-bundle repo org.nickvision.application-x64.flatpak org.nickvision.application
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: org.nickvision.application-x64.flatpak
