on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Linux
permissions:
  id-token: write
  contents: read
env:
  BUILD_TYPE: Release
  GITHUB_ACTIONS: true
jobs:
  build:
    name: "Build on x64"
    runs-on: ubuntu-latest
    container: 
      image: fedora:latest
      options: --privileged
    steps:
      - name: "Checkout"  
        uses: actions/checkout@v4
      - name: "Setup Environment"
        run: |
          mkdir build
          sudo dnf upgrade -y
          sudo dnf groupinstall "Development Tools" -y
          sudo dnf install git cmake gcc gcc-c++ curl zip unzip tar xdg-user-dirs gettext gettext-devel intltool glib2-devel gtk4 gtk4-devel libadwaita libadwaita-devel blueprint-compiler perl perl-FindBin perl-IPC-Cmd kernel-devel -y
          xdg-user-dirs-update
      - name: "Vcpkg"
        run: |
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg install libnick libxmlpp
      - name: "Build"
        run: |
          export VCPKG_ROOT=$(pwd)/vcpkg
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build .
      - name: "Install"
        run: |
          cd build
          cmake --install . --prefix "${{github.workspace}}/install"
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: ${{github.workspace}}/install
          name: Linux-x64-${{env.BUILD_TYPE}}