on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Linux
permissions:
  id-token: write
  contents: read
env:
  BUILD_TYPE: Release
  GITHUB_ACTIONS: true
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
jobs:
  build:
    name: "Build on x64"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"  
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "Setup Environment"
        run: |
          mkdir build
          sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa -y
          sudo apt-get update
          sudo apt-get install g++-13 gcc-13 xdg-user-dirs gettext tzdata locales libglib2.0-dev blueprint-compiler libgtk-4-dev libadwaita-1-dev -y
          xdg-user-dirs-update
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 --slave /usr/bin/g++ g++ /usr/bin/g++-13 --slave /usr/bin/gcov gcov /usr/bin/gcov-13
      - name: "Vcpkg"
        uses: johnwason/vcpkg-action@v5
        id: vcpkg
        with:
          pkgs: libnick libxmlpp
          triplet: x64-linux
          cache-key: ubuntu-latest
          revision: a1a1cbc975abf909a6c8985a6a2b8fe20bbd9bd6
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build"
        working-directory: ${{github.workspace}}/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build .
      - name: "Install"
        working-directory: ${{github.workspace}}/build
        run: cmake --install . --prefix "${{github.workspace}}/install"
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: ${{github.workspace}}/install
          name: Linux-x64-${{env.BUILD_TYPE}}