on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Linux
permissions:
  id-token: write
  contents: read
env:
  BUILD_TYPE: Release
  GITHUB_ACTIONS: true
jobs:
  build:
    name: "Build on x64"
    runs-on: ubuntu-latest
    container: 
      image: opensuse/tumbleweed:latest
      options: --privileged
    steps:
      - name: "Checkout"  
        uses: actions/checkout@v4
      - name: "Setup Environment"
        run: |
          mkdir build
          zypper ref -b && zypper dup -y
          zypper install gtk4-devel libadwaita libadwaita-devel xdg-desktop-portal-gnome webp-pixbuf-loader gettext flatpak-xdg-utils xdg-utils xdg-user-dirs xdg-user-dirs-gtk git libjack meson cmake cpp gcc gcc-c++ autoconf automake perl perl-FindBin perl-IPC-Cmd -y
          xdg-user-dirs-update
          xdg-user-dirs-gtk-update
          git clone https://gitlab.gnome.org/jwestman/blueprint-compiler
          meson "blueprint-compiler" build
          meson compile -C build
          meson install -C build --destdir /
      - name: "Vcpkg"
        run: |
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg install libnick libxmlpp
      - name: "Build"
        run: |
          export VCPKG_ROOT=$(pwd)/vcpkg
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX:PATH=$GITHUB_WORKSPACE/install
          cmake --build .
      - name: "Install"
        run: |
          cd build
          cmake --install .
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: $GITHUB_WORKSPACE/install
          name: Linux-x64-${{env.BUILD_TYPE}}