on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: macOS
permissions:
  id-token: write
  contents: read
env:
  GITHUB_ACTIONS: true
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
jobs:
  build:
    name: "Build on arm64"
    runs-on: macos-latest
    steps:
      - name: "Checkout"  
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "Setup Environment"
        run: |
          mkdir build
          brew install python-setuptools gettext yelp-tools
      - name: "Vcpkg"
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: libnick wxwidgets
          triplet: arm64-osx
          revision: 90ff15472a7c9f858717667b66403344e73cfb9c
          token: ${{ secrets.GITHUB_TOKEN }}
          github-binarycache: true
      - name: "Build"
        working-directory: ${{github.workspace}}/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ${{github.workspace}}/build/org.nickvision.application.osx/org.nickvision.application.osx.app
          name: macOS-arm64-Release