on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: macOS
permissions:
  id-token: write
  contents: read
jobs:
  tauri-macos:
    name: "Tauri on macOS"
    if: ${{ github.event.pull_request.user.login != 'weblate' }}
    strategy:
      fail-fast: false
      matrix:
        variant:
          - arch: arm64
            runner: macos-latest
          - arch: x64
            runner: macos-26-intel
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - uses: actions/checkout@v7
      - name: "Setup environment"
        run: |
          brew install gettext
          echo "$(brew --prefix gettext)/bin" >> "$GITHUB_PATH"
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri -> target
          key: ${{ matrix.variant.arch }}
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: npm
      - name: "Install frontend dependencies"
        run: npm ci
      - name: "Build"
        run: npm run tauri build
      - uses: actions/upload-artifact@v7
        with:
          name: Application-${{ matrix.variant.arch }}
          path: src-tauri/target/release/bundle/macos/*.app
