on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  schedule:
    - cron: '21 11 * * 0'
name: CodeQL
jobs:
  windows:
    name: Security Analysis
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login != 'weblate' }}
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.0.x
      # Setup CodeQL
      - name: Setup CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp
      # Restore
      - name: Restore GNOME
        run: dotnet restore NickvisionApplication.GNOME/NickvisionApplication.GNOME.csproj
      # Build
      - name: Build GNOME
        run: dotnet build NickvisionApplication.GNOME/NickvisionApplication.GNOME.csproj --configuration $env:Configuration --runtime linux-$env:Platform
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
      # Analyze
      - name: Analyze
        uses: github/codeql-action/analyze@v2
