on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  gnome-snap:
    name: "GNOME on Snap"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Build Test Application Snap
        uses: snapcore/action-build@v1
        id: snapcraft-build
        with:
          snapcraft-args: "-v"
      - uses: actions/upload-artifact@v4
        with:
          name: application-snap
          path: ${{ steps.snapcraft-build.outputs.snap }}    
