on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths:
      - "src-tauri/Cargo.lock"
      - "package-lock.json"
  push:
    branches: [ "main" ]
    paths:
      - "src-tauri/Cargo.lock"
      - "package-lock.json"
name: Sources
permissions:
  contents: write
  pull-requests: write
jobs:
  update-flatpak-sources:
    name: "Update Flatpak Sources"
    if: ${{ github.event.pull_request.user.login != 'weblate' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: "Install generators"
        run: |
          pip install tomlkit aiohttp
          git clone --depth 1 https://github.com/flatpak/flatpak-builder-tools.git /tmp/flatpak-builder-tools
          pip install /tmp/flatpak-builder-tools/node
      - name: "Update project dependencies"
        run: npm update && cd src-tauri && cargo update && cd ..
      - name: "Generate cargo-sources.json"
        run: python3 /tmp/flatpak-builder-tools/cargo/flatpak-cargo-generator.py src-tauri/Cargo.lock -o build-aux/flatpak/cargo-sources.json
      - name: "Generate node-sources.json"
        run: flatpak-node-generator npm package-lock.json -o build-aux/flatpak/node-sources.json
      - name: "Check for changes"
        id: diff
        run: echo "changed=$(git diff --quiet -- package-lock.json src-tauri/Cargo.lock build-aux/flatpak/cargo-sources.json build-aux/flatpak/node-sources.json && echo false || echo true)" >> "$GITHUB_OUTPUT"
      - name: "Commit to existing PR"
        if: steps.diff.outputs.changed == 'true' && github.event_name == 'pull_request'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package-lock.json src-tauri/Cargo.lock build-aux/flatpak/cargo-sources.json build-aux/flatpak/node-sources.json
          git commit -m "chore: Sync flatpak sources"
          git push
      - name: "Open PR with sync"
        if: steps.diff.outputs.changed == 'true' && github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: Sync flatpak sources"
          title: "chore: Sync flatpak sources"
          body: "Automated update of project dependencies (package-lock.json, src-tauri/Cargo.lock) and build-aux/flatpak/cargo-sources.json, build-aux/flatpak/node-sources.json to match."
          branch: sync-flatpak-sources
          add-paths: |
            package-lock.json
            src-tauri/Cargo.lock
            build-aux/flatpak/cargo-sources.json
            build-aux/flatpak/node-sources.json
