on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Windows
permissions:
  id-token: write
  contents: read
jobs:
  tauri-windows:
    name: "Tauri on Windows"
    if: ${{ github.event.pull_request.user.login != 'weblate' }}
    strategy:
      fail-fast: false
      matrix:
        variant:
          - arch: x64
            runner: windows-latest
            subsys: mingw64
            type: x86_64
          - arch: arm64
            runner: windows-11-arm
            subsys: clangarm64
            type: clang-aarch64
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - uses: actions/checkout@v7
      - uses: msys2/setup-msys2@v2
        id: msys2
        with:
          msystem: ${{ matrix.variant.subsys }}
          install: mingw-w64-${{ matrix.variant.type }}-gettext-tools
      - name: "Setup environment"
        shell: pwsh
        run: echo "${{ steps.msys2.outputs.msys2-location }}\${{ matrix.variant.subsys }}\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: npm
      - name: "Install frontend dependencies"
        run: npm ci
      - name: "Build"
        run: npm run tauri build
      - uses: actions/upload-artifact@v7
        with:
          name: Application-${{ matrix.variant.arch }}
          path: src-tauri/target/release/bundle/msi/*.msi
